apiVersion: v1
kind: Service
metadata:
  labels:
    app: es-kibana
  name: es-kibana-nodeport-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: 5601-5601
      port: 5601
      protocol: TCP
      targetPort: 5601
      nodePort: {{ .Values.kibanaNodePort }}
  selector:
    app: es-kibana
  type: NodePort